### ISSUE TITLE
Gif stays at a constant bpm and doesn't change to the song

### ISSUE THREAD

**Issue by SakuraBlisss** [cadon0/gif-to-the-beat#26]
So when I open it up, it gives me a brief message saying: 
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

The problem is that right after this message, the batch file begins to loop, giving me no time to input the command.
With this, the file stays in an infinite loop and effectively produces a gif for obs as it doesn't change its speed

Here is the infinite string of messages that I get:
Starting osu! memory reader...
Error:
  An assembly specified in the application dependencies manifest (GifToTheBeatDataProvider.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x86', version: '3.1.1'
    path: 'System.Diagnostics.StackTrace.dll'

Error running osu! memory reader:
Error: Command failed: C:\Users\Ty\Desktop\gif-to-the-beat-1.0.0\GifToTheBeatDataProvider.exe 7270
Error:
  An assembly specified in the application dependencies manifest (GifToTheBeatDataProvider.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x86', version: '3.1.1'
    path: 'System.Diagnostics.StackTrace.dll'

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 2147516556,
  signal: null,
  cmd: 'C:\\Users\\Ty\\Desktop\\gif-to-the-beat-1.0.0\\GifToTheBeatDataProvider.exe 7270'
}

**Comment by SakuraBlisss** [comment]
Update: Just had to delete the temp folder for the osumemoryreader. All fixed now!

**Comment by SakuraBlisss** [comment]
Update: Just had to delete the temp folder for the osumemoryreader. All fixed now!
